version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"


phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get install -y maven
    finally:
      - echo This always runs even if the update or install command fails.
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - mkdir target
      - chmod 777 target
      - echo "hello" >> abc.txt
      - echo "hi" >> hi.txt
    finally:
      - echo This always runs even if the install command fails.
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`

artifacts:
  files:
    - abc.txt
  discard-paths: yes
  secondary-artifacts:
    artifact1:
      files:
        - abc.txt
        - hi.txt
      discard-paths: yes
    artifact2:
      files:
        - abc.txt
        - hi.txt
      discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'